INSERT INTO _USER (username,password) VALUES ('admin','$2a$10$4Azwh9W8XHrF6yrYyodld.9vauxZqRe7oscKFCL26mKYlKPNKkhZK');
INSERT INTO _USER (username,password) VALUES ('user','$2a$10$nvo/FtE4L0oRrZzUXl/kJeMQqYkByqq48S20MOSTmvaVWqeMwPzpy');
INSERT INTO _ROLE (id,role) VALUES (0,'ADMIN');
INSERT INTO _ROLE (id,role) VALUES (1,'USER');
INSERT INTO USER_ROLES (user_id,role_id) VALUES ('admin',0);
INSERT INTO USER_ROLES (user_id,role_id) VALUES ('user',1);
INSERT INTO ACTIVITY (id,title,reference_code) VALUES (0,'Mercadona España','^[1-5]$'); 
INSERT INTO ACTIVITY (id,title,reference_code) VALUES (1,'Mercadona Portugal','^[6]$'); 
INSERT INTO ACTIVITY (id,title,reference_code) VALUES (2,'Almacenes','^[7]$');
INSERT INTO ACTIVITY (id,title,reference_code) VALUES (3,'Oficinas Mercadona','^[8]$'); 
INSERT INTO SUPPLIER (id,title,address) VALUES (0,'DEFAULT',NULL);
INSERT INTO SUPPLIER (id,title,address) VALUES (4444444,'Covap','Direccion');
INSERT INTO SUPPLIER (id,title,address) VALUES (8437008,'Hacendado','Calle Valencia, 5. Tabernes Blanques, Valencia. España');
INSERT INTO ITEM (id,title,description) VALUES (1,'Gazpacho','Gazpacho fresco');
INSERT INTO ITEM (id,title,description) VALUES (2,'Queso','Queso fresco');
INSERT INTO ITEM (id,title,description) VALUES (3,'Leche','Leche entera');